# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 15:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment2Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('marker_map', models.PositiveIntegerField(default=0)),
                ('tag0', models.BooleanField(default=0)),
                ('tag1', models.BooleanField(default=0)),
                ('tag2', models.BooleanField(default=0)),
                ('tag3', models.BooleanField(default=0)),
                ('tag4', models.BooleanField(default=0)),
                ('tag5', models.BooleanField(default=0)),
                ('tag6', models.BooleanField(default=0)),
                ('tag7', models.BooleanField(default=0)),
                ('tag8', models.BooleanField(default=0)),
                ('tag9', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('abstract', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SceneItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('parenthetical', models.CharField(blank=True, max_length=100)),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workingtitle', models.CharField(max_length=30)),
                ('abstract', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('autor', models.CharField(blank=True, max_length=300)),
                ('version', models.CharField(blank=True, max_length=300)),
                ('copyright', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.BaseModel')),
                ('time_all', models.DateTimeField(blank=True, null=True)),
                ('duration_all', models.DurationField(blank=True, null=True)),
            ],
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.BaseModel')),
                ('progress', models.PositiveSmallIntegerField(default=0)),
            ],
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='Gadget',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.BaseModel')),
                ('progress', models.PositiveSmallIntegerField(default=0)),
            ],
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.BaseModel')),
            ],
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.BaseModel')),
                ('contact', models.CharField(blank=True, max_length=1000)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.BaseModel')),
                ('color', models.PositiveIntegerField(default=16777215)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Person')),
                ('gadgets', models.ManyToManyField(blank=True, to='app.Gadget')),
            ],
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.BaseModel')),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.TextField(blank=True)),
                ('variantmap', models.PositiveIntegerField(default=0)),
                ('intent', models.PositiveIntegerField(default=0)),
                ('color', models.PositiveIntegerField(default=0)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('progress_script', models.PositiveSmallIntegerField(default=0)),
                ('progress_pre', models.PositiveSmallIntegerField(default=0)),
                ('progress_shot', models.PositiveSmallIntegerField(default=0)),
                ('progress_post', models.PositiveSmallIntegerField(default=0)),
                ('audios', models.ManyToManyField(blank=True, to='app.Audio')),
                ('gadgets', models.ManyToManyField(blank=True, to='app.Gadget')),
                ('persons', models.ManyToManyField(blank=True, to='app.Person')),
                ('roles', models.ManyToManyField(blank=True, to='app.Role')),
            ],
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='SFX',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.BaseModel')),
                ('progress', models.PositiveSmallIntegerField(default=0)),
            ],
            bases=('app.basemodel',),
        ),
        migrations.AddField(
            model_name='project',
            name='script',
            field=models.ManyToManyField(blank=True, to='app.Script'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.BaseModel'),
        ),
        migrations.AddField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Poll'),
        ),
        migrations.AddField(
            model_name='script',
            name='persons',
            field=models.ManyToManyField(blank=True, to='app.Person'),
        ),
        migrations.AddField(
            model_name='sceneitem',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Role'),
        ),
        migrations.AddField(
            model_name='sceneitem',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Scene'),
        ),
        migrations.AddField(
            model_name='scene',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Script'),
        ),
        migrations.AddField(
            model_name='scene',
            name='set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Location'),
        ),
        migrations.AddField(
            model_name='scene',
            name='sfxs',
            field=models.ManyToManyField(blank=True, to='app.SFX'),
        ),
        migrations.AddField(
            model_name='location',
            name='persons',
            field=models.ManyToManyField(blank=True, to='app.Person'),
        ),
        migrations.AddField(
            model_name='appointment2scene',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Appointment'),
        ),
        migrations.AddField(
            model_name='appointment2scene',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Scene'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='gadgets',
            field=models.ManyToManyField(blank=True, to='app.Gadget'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='meeting_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Location'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='persons',
            field=models.ManyToManyField(blank=True, to='app.Person'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='scenes',
            field=models.ManyToManyField(blank=True, null=True, through='app.Appointment2Scene', to='app.Scene'),
        ),
    ]
