# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_JK'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='tag0',
            field=models.BooleanField(default=0, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='tag1',
            field=models.BooleanField(default=0, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='tag2',
            field=models.BooleanField(default=0, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='tag3',
            field=models.BooleanField(default=0, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='tag4',
            field=models.BooleanField(default=0, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='tag5',
            field=models.BooleanField(default=0, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='tag6',
            field=models.BooleanField(default=0, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='tag7',
            field=models.BooleanField(default=0, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='tag8',
            field=models.BooleanField(default=0, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='tag9',
            field=models.BooleanField(default=0, verbose_name=''),
        ),
    ]
