# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_JK'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DialogItem',
            new_name='SceneItem',
        ),
        migrations.RemoveField(
            model_name='script',
            name='scenes',
        ),
        migrations.AddField(
            model_name='scene',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Script'),
        ),
    ]
