# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_JK'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemodel',
            name='tag10',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AddField(
            model_name='basemodel',
            name='tag11',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
    ]
