# Generated by Django 6.1.1 on 2026-10-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('X', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='sceneitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
