# Generated by Django 6.1.1 on 2026-10-05 20:48

import colorfield.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('X', '0002_scene_item_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='arc_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='role',
            name='wardrobe',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sceneitem',
            name='gadget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='X.gadget'),
        ),
        migrations.AddField(
            model_name='sceneitem',
            name='sfx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='X.sfx'),
        ),
        migrations.AddField(
            model_name='script',
            name='revision_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='script',
            name='revision_label',
            field=models.CharField(blank=True, default='White', max_length=50),
        ),
        migrations.CreateModel(
            name='ScriptRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='X.script')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
